### PR TITLE
Use exjsx instead of deprecated jsex

### PR DESCRIPTION
**Pull request by guilleiguaran**

### CODE REVIEW

**Comment by mobileoverlord** [comment]
+1

**Comment by slogsdon** [comment]
Sorry for the wait. I can get a new version pushed to Hex this evening.

**Comment by mobileoverlord** [comment]
np for me, just getting this going now. Hackney is a little out of date too, might PR that soon :)

**Comment by slogsdon** [comment]
@guilleiguaran, @mobileoverlord: There is a new version available now on Hex. Thanks again for the contributions!

**Pull request merged**
